//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.16 at 05:48:13 PM ICT 
//


package com.vn2bs.nsw_gateway.xsd.bct.thutuc1;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vn2bs.nsw_gateway.xsd.bct.thutuc1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vn2bs.nsw_gateway.xsd.bct.thutuc1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TraLoiRequest }
     * 
     */
    public TraLoiRequest createTraLoiRequest() {
        return new TraLoiRequest();
    }

    /**
     * Create an instance of {@link TraLoiResponse }
     * 
     */
    public TraLoiResponse createTraLoiResponse() {
        return new TraLoiResponse();
    }

}
