//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.11 at 11:54:50 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "thutuc1.bct.xsd.nsw_gateway.vn2bs.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vn2bs.nsw_gateway.xsd.bct.thutuc1;
