spring.application.name=nsw-gateway
server.port=8084

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=bct

# JPA Configuration
spring.datasource.url=jdbc:mysql://localhost:3316/nsw_adapter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update

# MinIO Configuration
minio.url=http://localhost:9000
minio.username=minioadmin
minio.password=minioadmin

# Liquibase Configuration
spring.liquibase.change-log=classpath:config/liquibase/master.xml

# Disable Liquibase by default (enable in production if needed)
spring.liquibase.enabled=false
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${spring.datasource.username}
spring.liquibase.password=${spring.datasource.password}
spring.liquibase.driver-class-name=${spring.datasource.driver-class-name}