url=jdbc:mysql://localhost:3316/nsw_adapter?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
username=root
password=rootpassword
driver=com.mysql.cj.jdbc.Driver

changeLogFile=src/main/resources/config/liquibase/master.xml