spring.application.name=bct-gateway
server.port=8081

# JPA Configuration
spring.datasource.url=jdbc:mysql://localhost:3326/bct_adapter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update

# Disable Liquibase by default (enable in production if needed)
spring.liquibase.enabled=false