events {}

http {
    upstream nsw-gateway {
        server nsw-gateway:8084;
    }

    upstream nsw-adapter {
        server nsw-adapter:8083;
    }

    upstream bct-gateway {
        server bct-gateway:8081;
    }

    upstream bct-adapter {
        server bct-adapter:8082;
    }

    upstream minio {
        server minio:9001;
    }

    server {
        listen 80;

        location /nsw-gateway {
            proxy_pass http://nsw-gateway;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /nsw-adapter {
            proxy_pass http://nsw-adapter;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /bct-gateway {
            proxy_pass http://bct-gateway;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /bct-adapter {
            proxy_pass http://bct-adapter;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /minio {
            proxy_pass http://minio;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
