//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.16 at 05:48:38 PM ICT 
//


package com.vn2bs.bct_gateway.xsd.bct.guihoso;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="maSoHoSo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tenNguoiGui" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maSoHoSo",
    "tenNguoiGui"
})
@XmlRootElement(name = "GuiHoSoRequest")
public class GuiHoSoRequest {

    @XmlElement(required = true)
    protected String maSoHoSo;
    @XmlElement(required = true)
    protected String tenNguoiGui;

    /**
     * Gets the value of the maSoHoSo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaSoHoSo() {
        return maSoHoSo;
    }

    /**
     * Sets the value of the maSoHoSo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaSoHoSo(String value) {
        this.maSoHoSo = value;
    }

    /**
     * Gets the value of the tenNguoiGui property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenNguoiGui() {
        return tenNguoiGui;
    }

    /**
     * Sets the value of the tenNguoiGui property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenNguoiGui(String value) {
        this.tenNguoiGui = value;
    }

}
