//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.16 at 05:48:38 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "guihoso.bct.xsd.nsw_gateway.vn2bs.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vn2bs.bct_gateway.xsd.bct.guihoso;
